version: '1'
services:
  #Bimba 
  bimba-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development
    #image: php:8.1-fpm
    container_name: bimba-backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    networks:
      - app-network
    volumes:
      - ./:/var/www/html

  #MySql Service
#  mysql-service:
#    image: mysql:8
#    container_name: mysql-service
#    restart: unless-stopped
#    command: --default-authentication-plugin=mysql_native_password
#    tty: true
#    environment:
#      MYSQL_ROOT_PASSWORD: 'mysql'
#      MYSQL_DATABASE: bimba
#    ports:
#      - 3306:3306
#    networks:
#      - app-network
#    volumes:
#      - ./mysql-datadir/:/var/lib/mysql/

  #Queue worker
  bimba-queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development
    container_name: bimba-queue-worker
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    command: php artisan queue:work
    networks:
      - app-network
    volumes:
      - ./:/var/www/html

  # Redis
  redis:
    image: redis:5.0.8-alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  #Nginx Service
  nginx-service:
    image: nginx:alpine
    container_name: nginx-service
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
